### ISSUE TITLE
Basic mouse support?

### ISSUE THREAD

**Issue by enthus1ast** [johnnovak/illwill#8]
It would be super awesome if illwill could emit basic mouse events!
Any chance this will be implemented? :)

**Comment by enthus1ast** [comment]
added experimental mouse support for linux https://github.com/enthus1ast/illwill

**Comment by enthus1ast** [comment]
https://github.com/enthus1ast/illwillWidgets

**Comment by 0xACE** [comment]
Example link can be found here:
https://github.com/enthus1ast/illwill/blob/master/examples/mouse.nim

+1 from me to get it merged upstream...

**Comment by enthus1ast** [comment]
not ready yet for pr:
- [x] mod keys (shift, ctrl) linux
- [x] windows support
- [x] test on mac
- [x] test in putty (putty does not implement SET_ANY_EVENT_MOUSE, so no hover)
- [x] cleanup

**Comment by skellock** [comment]
Works well on the mac (10.15.2).  Tried `fish`, `bash`, and `zsh`.  Also tried in & out of `tmux`.

Well done.

![illwill-mouse](https://user-images.githubusercontent.com/68273/73450041-85c61b00-4332-11ea-8a08-2309ec26fd5f.gif)

Edit 1:  Tried in `iTerm2` and the built-in `terminal` apps.

**Comment by enthus1ast** [comment]
added windows support https://github.com/enthus1ast/illwill

**Comment by johnnovak** [comment]
@enthus1ast illwillWidgets looks quite cool! I'll play around a bit with it later when I'll have some time!
